/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sms;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
/**
 *
 * @author Hasib
 */
   /**
    * calculate and shows the overall grade 
    * its from teacher panel 
    */
public class result2 extends javax.swing.JFrame {

    /** Creates new form result2 */
    public result2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        cl = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        m = new javax.swing.JTextField();
        s = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        r = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        t = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Result prepare module");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 466, 66));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 135, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 181, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Class:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("English");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Math");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Science");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 390, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Religion");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 390, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Bangla");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 390, -1, -1));

        id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 132, 252, -1));

        cl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 240, 252, -1));

        name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 178, 252, -1));

        m.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 430, 94, 52));

        s.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 430, 94, 52));

        b.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 430, 94, 52));

        e.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 430, 94, 52));

        r.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(r, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 430, 94, 52));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 153));
        jLabel10.setText("Marks");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 306, 139, 66));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("generate result grade");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 243, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("Save");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 243, -1));

        t.setColumns(20);
        t.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t.setRows(5);
        t.setText("            \n    \n                     ");
        jScrollPane2.setViewportView(t);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 170, 320, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("Back");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 68, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("Close");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 40, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   /**
    * calculate and shows the overall grade 
    */
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String sid=id.getText();//id
        String nam=name.getText();//username
        String cls=cl.getText();//class

        String eng = e.getText();
        double en= Double.parseDouble(eng);
        String mat = m.getText();
        double ma= Double.parseDouble(mat);
        String sci = s.getText();
        double sc= Double.parseDouble(sci);
        String rel= r.getText();
        double re= Double.parseDouble(rel);
        String ban= b.getText();
        double ba= Double.parseDouble(ban);

        double total=en+ba+re+sc+ma;
        double av=total/5;

        String grade;

        if(av>= 80){
            grade= "A+";
        }
        else if(av>=70 && av <80){
            grade="A";
        }

        else if(av>=60 && av <70){
            grade="B";
        }

        else if(av>=50 && av<60){
            grade="C";
        }

        else if(av>=40 && av<50){
            grade="D";
        }
        else
        {
            grade="Fail";
        }

        t.setText("\t\n"+grade);
    }//GEN-LAST:event_jButton1MouseClicked
  /**
   * stores the marks into database
   */
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String sid=id.getText();//id
        String nam=name.getText();//username
        String cls=cl.getText();//class

        String eng = e.getText();
        double en= Double.parseDouble(eng);
        String mat = m.getText();
        double ma= Double.parseDouble(mat);
        String sci = s.getText();
        double sc= Double.parseDouble(sci);
        String rel= r.getText();
        double re= Double.parseDouble(rel);
        String ban= b.getText();
        double ba= Double.parseDouble(ban);

        double total=en+ba+re+sc+ma;
        double av=total/5;

        String grade;

        if(av>= 80){
            grade= "A+";
        }
        else if(av>=70 && av <80){
            grade="A";
        }

        else if(av>=60 && av <70){
            grade="B";
        }

        else if(av>=50 && av<60){
            grade="C";
        }

        else if(av>=40 && av<50){
            grade="D";
        }
        else
        { grade="Fail";
        }

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/scl","root","");
            String sql= "insert into result values(?,?,?,?,?,?,?,?,?)";
            PreparedStatement ptst = conn.prepareStatement(sql);

            ptst.setString(1,id.getText());
            ptst.setString(2,name.getText());
            ptst.setString(3,cl.getText());
            ptst.setDouble(4,en);
            ptst.setDouble(5,ma);
            ptst.setDouble(6,sc);
            ptst.setDouble(7,ba);
            ptst.setDouble(8,re);
            ptst.setString(9,grade);
            ptst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data has been stored successfully!");
            conn.close();

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2MouseClicked
    /**
     * returns to teacher panel
     */
    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        welcome2 frame =new welcome2();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked
   /**
    * close the program
    */
    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(result2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(result2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(result2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(result2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new result2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b;
    private javax.swing.JTextField cl;
    private javax.swing.JTextField e;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField m;
    private javax.swing.JTextField name;
    private javax.swing.JTextField r;
    private javax.swing.JTextField s;
    private javax.swing.JTextArea t;
    // End of variables declaration//GEN-END:variables

}
